---
defaults:
  smtp:
    address: <%= ENV.fetch("SMTP_ADDRESS", "mail.yourdomain.edu") %>
    port: <%= ENV.fetch("SMTP_PORT", 465) %>
    authentication: <%= ENV.fetch("SMTP_AUTH", "plain") %>
    user_name: <%= ENV.fetch("SMTP_USERNAME", "someuser") %>
    password: <%= ENV.fetch("SMTP_PASSWORD", "itsasecret") %>
    domain: <%= ENV.fetch("SMTP_DOMAIN", "yourdomain.edu") %>
    enable_starttls_auto: <%= ENV.fetch("SMTP_STARTTLS", true) %>
    openssl_verify_mode: <%= ENV.fetch("SMTP_SSL_VERIFY", "none") %>
  default_options:
    outgoing_address: <%= ENV.fetch("SMTP_FROM", "Canvas Rollcall <canvas@yourdomain.edu>") %>

development:
  <<: *defaults

test: &test
  <<: *defaults

cucumber:
  <<: *test

production:
  <<: *defaults
